import type { Order } from "../models/order";
export const fakeOrders: Order[] = [
  {
    status: "In oven",
    customerName: "Buu",
    phone: "123456789",
    address: "Mesa, Az , USA",
    priority: true,
    estimatedDelivery: "2027-04-25T10:00:00",
    cart: [
      {
        productID: 7,
        productName: "Banh Chung",
        quantity: 3,
        unitPrice: 16,
        totalPrice: 48,
      },
      {
        productID: 5,
        productName: "Banh Chuoi",
        quantity: 2,
        unitPrice: 16,
        totalPrice: 32,
      },
      {
        productID: 3,
        productName: "Banh Dau Xanh",
        quantity: 1,
        unitPrice: 15,
        totalPrice: 15,
      },
    ],
    position: "-9.000,38.000",
    orderPrice: 95,
    priorityPrice: 19,
  },
  {
    status: "Received",
    customerName: "David",
    phone: "123456789",
    address: "Mesa, Az , USA",
    priority: false,
    estimatedDelivery: "2027-04-25T10:00:00",
    cart: [
      {
        productID: 7,
        productName: "Banh Chung",
        quantity: 3,
        unitPrice: 16,
        totalPrice: 48,
      },
      {
        productID: 5,
        productName: "Banh Chuoi",
        quantity: 2,
        unitPrice: 16,
        totalPrice: 32,
      },
      {
        productID: 3,
        productName: "Banh Dau Xanh",
        quantity: 1,
        unitPrice: 15,
        totalPrice: 15,
      },
    ],
    position: "-9.000,38.000",
    orderPrice: 95,
    priorityPrice: 19,
  },
  {
    status: "Delivered",
    customerName: "Kim",
    phone: "123456789",
    address: "Mesa, Az , USA",
    priority: true,
    estimatedDelivery: "2027-04-25T10:00:00",
    cart: [
      {
        productID: 7,
        productName: "Banh Chung",
        quantity: 3,
        unitPrice: 16,
        totalPrice: 48,
      },
      {
        productID: 5,
        productName: "Banh Chuoi",
        quantity: 2,
        unitPrice: 16,
        totalPrice: 32,
      },
      {
        productID: 3,
        productName: "Banh Dau Xanh",
        quantity: 1,
        unitPrice: 15,
        totalPrice: 15,
      },
    ],
    position: "-9.000,38.000",
    orderPrice: 95,
    priorityPrice: 19,
  },
];
